name: Friend Circle Lite

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  friend-circle-lite:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Latest Repository
      uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check RSS feeds
      env:
        SMTP_PWD: ${{ secrets.SMTP_PWD }}
      run: |
        python run.py
        
    - name: git config
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Commit changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git add .
        git commit -m "⏱️GitHub Action定时更新"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git main
